name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - run: pip install -r requirements_dev.txt

      - run: mypy --ignore-missing-imports .
